<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5388" started-at="2018-08-08T10:09:49Z" finished-at="2018-08-08T10:09:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5388" started-at="2018-08-08T10:09:49Z" finished-at="2018-08-08T10:09:54Z">
      <class name="com.veryemp.testscripts.AppliedForJob">
        <test-method status="PASS" signature="loginApi()[pri:0, instance:com.veryemp.testscripts.AppliedForJob@23e028a9]" name="loginApi" duration-ms="4820" started-at="2018-08-08T10:09:49Z" description="Valid Login scenario with valid credentials" finished-at="2018-08-08T10:09:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginApi -->
        <test-method status="FAIL" signature="successMessageAppliedForJob()[pri:1, instance:com.veryemp.testscripts.AppliedForJob@23e028a9]" name="successMessageAppliedForJob" duration-ms="518" started-at="2018-08-08T10:09:54Z" description="Applied For Job" finished-at="2018-08-08T10:09:54Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<false> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<false> but was:<true>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:71)
at com.veryemp.testscripts.AppliedForJob.successMessageAppliedForJob(AppliedForJob.java:94)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successMessageAppliedForJob -->
      </class> <!-- com.veryemp.testscripts.AppliedForJob -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
